sudo: required

language: python

cache: pip

python:
  - "3.6" # rhel 7/epel, ubuntu 16.04 and 18.04, alpine 3.7-3.9
  - "3.7" # alpine 3.10

install:
  - sudo apt-get install libcmph0 libcmph-dev


script:
  - cmake .
  - make
  - ls -alh
  - ./test-create-and-query.o output.ddb src/tests/input.txt
  - python3 src/tests/create_large_random_key_value_file.py src/tests/big.txt 90000
  - cat src/tests/input.txt src/tests/big.txt > src/tests/combined.txt
  - ./test-create-and-query.o combined.ddb src/tests/combined.txt
  - ls -alh
  - sudo install libdiscodb.so /usr/lib/libdiscodb.so
  - sudo install src/*.h /usr/include/.
  - cd python
  - python3 setup.py bdist_wheel
  - find . -name "*.so" | xargs -P1 -n1 ldd
  - pip3 install --force-reinstall dist/discodb*.whl
  - python3 util/test_merge.py


